

Import('env')

lib_src = [
			'Sphere.cpp',
			'SphereTree.cpp',
			'ClosestPointQuery.cpp'
			]
lib_target = 'core'

env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')

lib = env.StaticLibrary(source = lib_src , target = lib_target)
